"""empty message

Revision ID: 777b074d03b0
Revises: 909a0ad6bd37
Create Date: 2021-06-23 07:28:04.366375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777b074d03b0'
down_revision = '909a0ad6bd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('Start_Time', sa.DateTime(), nullable=False),
    sa.Column('Artist_ID ', sa.Integer(), nullable=True),
    sa.Column('Venue_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Artist_ID '], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['Venue_ID'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    op.drop_table('Show')
    # ### end Alembic commands ###
