"""change table

Revision ID: 909a0ad6bd37
Revises: 3c85e4edf664
Create Date: 2021-06-20 15:10:32.444095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909a0ad6bd37'
down_revision = '3c85e4edf664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=130), nullable=True))
    op.add_column('Artist', sa.Column('Looking_Venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=320), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=130), nullable=True))
    op.add_column('Venue', sa.Column('Looking_Venues', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'Looking_Venues')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'Looking_Venues')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
